name: check-codebase

on:
  push:

permissions:
  contents: read

jobs:
  check-codebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          version: ".bun-version"

      - name: Install deps
        run: bun install

      - name: Run lint
        run: bun lint

      - name: Run format
        run: bun format
